version: '2'

services: 
  # this is our kafka cluster
  kafka-cluster:
    image: landoop/fast-data-dev:cp3.3.0
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0     # Disable Running test so the cluster starts faster
      FORWARDLOGS: 0  # Disable running 5 file sources connectors that brings application logs ..
      SAMPLEDATA: 0   # Do not create sea_vessel_position_reports, nyc_yellow_taxi_trips ...
    ports:
      - 2181:2181            # Zookeeper
      - 3030:3030            # Landoop UI
      - 8081-8083:8081-8083  # REST Proxy, Schema Registry, Kafka Connector ports
      - 9581-9585:9581-9585  # JMX Ports
      - 9092:9092            # Kafka Brokers
      